### ISSUE TITLE
Is it possible to combine @generated with @i

### ISSUE THREAD

**Issue by quantumlang** [JuliaReverse/NiLangTutorial#3]
`Base.Cartesian` module offers some handy macros to work with arbitrary dimension array, e.g. I can write a general array summation function
```julia
using Base.Cartesian

@generated function add!(A!::AbstractArray{V, N}, B, C) where {V, N}
    return quote
        @assert size(A!)==size(B)==size(C)
        @nloops $N i A! begin
            @nref($N, A!, i) = @nref($N, B, i) + @nref($N, C, i)
        end
    end
end
```

Is it possible for me to write something like this to generate reversible functions ?
```julia
using NiLang
using Base.Cartesian

@generated @i function add!(A!::AbstractArray{V, N}, B, C) where {V, N}
    return quote
        @assert size(A!)==size(B)==size(C)
        @nloops $N i A! begin
            @nref($N, A!, i) += @nref($N, B, i)
            @nref($N, A!, i) += @nref($N, C, i)
        end
    end
end
```

> The above code currently won't work

**Comment by GiggleLiu** [comment]
macros before a function are not supported by `@generated`. @Roger-luo do you have any good design pattern to let macros play well with generated functions?

**Comment by GiggleLiu** [comment]
But I think it is reasonable to get `@nexpr` supported in NiLang.

See this patch: 
https://github.com/GiggleLiu/NiLangCore.jl/pull/23

I just let the automatically generate `nothing` expression pass NiLang's compiler. It will be tagged in several hours.

**Comment by quantumlang** [comment]
Thanks for supporting this :) 
I think the problem associated with `@generated` macro can be partly addressed by writing it as
```julia
for N=[2, 3, 4]
    eval(
    quote
        @i function add!(A!::AbstractArray{V, $N}, B, C) where {V}
                @safe @assert size(A!)==size(B)==size(C)
                @nloops $N i A! begin
                    @nref($N, A!, i) += @nref($N, B, i)
                    @nref($N, A!, i) += @nref($N, C, i)
                end
            end
        end
    ) 
end
```

**Comment by Roger-luo** [comment]
@GiggleLiu you need to rewrite the compiler in YaoLang's way on SSA to play with generated functions.

**Comment by GiggleLiu** [comment]
@quantumlang The work around does not look too bad. And thank you too for let me notice that the `nothing` statement should be allowed in NiLang.

@Roger-luo Thanks. It sounds like a huge project. :disappointed:

**Comment by Roger-luo** [comment]
also IMHO, why can't you just use

```julia
function add!(A!::AbstractArray{V, N}, B, C) where {V, N}
        @assert size(A!)==size(B)==size(C)
        @nloops N i A! begin
            @nref(N, A!, i) = @nref(N, B, i) + @nref(N, C, i)
        end
end
```

you are not using any type information to generate the program. Returning the en expression directly has no difference with just write the function.

**Comment by Roger-luo** [comment]
also note `@generated` means generate some customized code during type inference, but since NiLang doesn't have its own type system, this can break the condition that `@i` is purely reversible, since in a real generated function use case you  usually need to calculate something based on the type information, but note Julia's type system is not purely reversible

using a linear type like representation can solve the problem potentially, which is what I mean here a SSA, not just because `@generated` function needs SSA to expand the expression.

**Comment by GiggleLiu** [comment]
```julia
julia> function add!(A!::AbstractArray{V, N}, B, C) where {V, N}
               @assert size(A!)==size(B)==size(C)
               @nloops N i A! begin
                   @nref(N, A!, i) = @nref(N, B, i) + @nref(N, C, i)
               end
       end
ERROR: LoadError: MethodError: no method matching _nloops(::Symbol, ::Symbol, ::Symbol, ::Expr)
Closest candidates are:
  _nloops(::Int64, ::Symbol, ::Symbol, ::Expr...) at cartesian.jl:42
  _nloops(::Int64, ::Symbol, ::Expr, ::Expr...) at cartesian.jl:47
Stacktrace:
 [1] @nloops(::LineNumberNode, ::Module, ::Any, ::Any, ::Any, ::Expr) at ./cartesian.jl:39
in expression starting at REPL[4]:3

```
The problem is, `N` can not be a symbol. Although I think it should be doable for Julia compiler to evaluate `N` during type inference.

**Comment by Roger-luo** [comment]
this is not during type inference, this is executed during parsing. it's not possible to know `N` during parsing. If you don't want to rewrite the compiler in SSA, the only way is to special case all the macros here, so they get expanded inside NiLang. This partly solve the problem that `@generated` functions can create a program that is not actually reversible.

In YaoLang's approach, this will be just expanded as normal Julia macro which I think is more elegant and easier tho.

**Comment by Roger-luo** [comment]
Oh actually, you can also expand the macros inside a `@generated` function using `Meta.lower` manually which will return a SSA. But then NiLang needs to be able to handle that SSA IR.

**Comment by GiggleLiu** [comment]
Yeah, I mean it should make the life easier to have a special evaluation expression like `$!` that
```julia
function add!(A!::AbstractArray{V, N}, B, C) where {V, N}
               @assert size(A!)==size(B)==size(C)
               @nloops $!(N) i A! begin
                   @nref($!(N), A!, i) = @nref($!(N), B, i) + @nref($!(N), C, i)
               end
       end
```

1. macro expand,
2. function dispatch, and types are known,
3. `$!TYPE_PARAMETER` expanded and function generated.

We can write much less generate function with this new evaluation expression, do you think it make sense to let it be a part of Julia language?

PS: don't huyou me to re-write NiLang compiler. :P

**Comment by Roger-luo** [comment]
no you won't be able to do this since `$!N` is an expression that has to be expanded during parsing, the type inference stage is done on SSA not Expr, you just don't have that anymore.

Or this has to be done at the cost to save all expressions in RAM, as a result I can expect a significant slow down on the compilation

**Comment by GiggleLiu** [comment]
I c, thanks!
